/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContinueRouteImport } from './routes/continue'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R2faRouteImport } from './routes/2fa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachersIndexRouteImport } from './routes/teachers/index'
import { Route as InstructorIndexRouteImport } from './routes/instructor/index'
import { Route as FacilitatorIndexRouteImport } from './routes/facilitator/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'
import { Route as LearnMineRouteImport } from './routes/learn/mine'
import { Route as InstructorsIdRouteImport } from './routes/instructors.$id'
import { Route as InstructorProfileRouteImport } from './routes/instructor/profile'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as CheckoutCallbackRouteImport } from './routes/checkout.callback'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminIntegrityRouteImport } from './routes/admin/integrity'
import { Route as TeachersPathsIndexRouteImport } from './routes/teachers/paths/index'
import { Route as TeachersCoursesIndexRouteImport } from './routes/teachers/courses/index'
import { Route as TeachersCohortsIndexRouteImport } from './routes/teachers/cohorts/index'
import { Route as InstructorPathsIndexRouteImport } from './routes/instructor/paths/index'
import { Route as InstructorEarningsIndexRouteImport } from './routes/instructor/earnings/index'
import { Route as InstructorCoursesIndexRouteImport } from './routes/instructor/courses/index'
import { Route as InstructorCohortsIndexRouteImport } from './routes/instructor/cohorts/index'
import { Route as InstructorAnalyticsIndexRouteImport } from './routes/instructor/analytics/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminPayoutsIndexRouteImport } from './routes/admin/payouts/index'
import { Route as AdminPathsIndexRouteImport } from './routes/admin/paths/index'
import { Route as AdminEarningsIndexRouteImport } from './routes/admin/earnings/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AdminCohortsIndexRouteImport } from './routes/admin/cohorts/index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin/analytics/index'
import { Route as TeachersPathsSlugRouteImport } from './routes/teachers/paths/$slug'
import { Route as TeachersCoursesSlugRouteImport } from './routes/teachers/courses/$slug'
import { Route as TeachersCohortsSlugRouteImport } from './routes/teachers/cohorts/$slug'
import { Route as LearnProjectProjectIdRouteImport } from './routes/learn/project/$projectId'
import { Route as LearnPeerReviewProjectIdRouteImport } from './routes/learn/peer-review/$projectId'
import { Route as LearnPathPathIdRouteImport } from './routes/learn/path/$pathId'
import { Route as LearnLessonLessonIdRouteImport } from './routes/learn/lesson/$lessonId'
import { Route as LearnGroupsGroupIdRouteImport } from './routes/learn/groups/$groupId'
import { Route as LearnCourseCourseIdRouteImport } from './routes/learn/course/$courseId'
import { Route as LearnCohortCohortIdRouteImport } from './routes/learn/cohort/$cohortId'
import { Route as LearnAssessmentAssessmentIdRouteImport } from './routes/learn/assessment/$assessmentId'
import { Route as InstructorProjectsProjectIdRouteImport } from './routes/instructor/projects/$projectId'
import { Route as InstructorProjectSubmissionsProjectIdRouteImport } from './routes/instructor/project-submissions/$projectId'
import { Route as InstructorPathsPathIdRouteImport } from './routes/instructor/paths/$pathId'
import { Route as InstructorLessonsLessonIdRouteImport } from './routes/instructor/lessons/$lessonId'
import { Route as InstructorCoursesCourseIdRouteImport } from './routes/instructor/courses/$courseId'
import { Route as InstructorCohortsCohortIdRouteImport } from './routes/instructor/cohorts/$cohortId'
import { Route as InstructorAttemptReportsAssessmentIdRouteImport } from './routes/instructor/attempt-reports/$assessmentId'
import { Route as InstructorAssessmentsAssessmentIdRouteImport } from './routes/instructor/assessments/$assessmentId'
import { Route as FacilitatorCohortsCohortIdRouteImport } from './routes/facilitator/cohorts/$cohortId'
import { Route as AdminProjectsProjectIdRouteImport } from './routes/admin/projects/$projectId'
import { Route as AdminProjectSubmissionsProjectIdRouteImport } from './routes/admin/project-submissions/$projectId'
import { Route as AdminPathsPathIdRouteImport } from './routes/admin/paths/$pathId'
import { Route as AdminLessonsLessonIdRouteImport } from './routes/admin/lessons/$lessonId'
import { Route as AdminCoursesCourseIdRouteImport } from './routes/admin/courses/$courseId'
import { Route as AdminCohortsCohortIdRouteImport } from './routes/admin/cohorts/$cohortId'
import { Route as AdminBlogPostIdRouteImport } from './routes/admin/blog/$postId'
import { Route as AdminAttemptReportsAssessmentIdRouteImport } from './routes/admin/attempt-reports/$assessmentId'
import { Route as AdminAssessmentsAssessmentIdRouteImport } from './routes/admin/assessments/$assessmentId'
import { Route as InstructorAnalyticsEntityTypeEntityIdRouteImport } from './routes/instructor/analytics/$entityType.$entityId'
import { Route as AdminAnalyticsEntityTypeEntityIdRouteImport } from './routes/admin/analytics/$entityType.$entityId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinueRoute = ContinueRouteImport.update({
  id: '/continue',
  path: '/continue',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R2faRoute = R2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorIndexRoute = InstructorIndexRouteImport.update({
  id: '/instructor/',
  path: '/instructor/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitatorIndexRoute = FacilitatorIndexRouteImport.update({
  id: '/facilitator/',
  path: '/facilitator/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnMineRoute = LearnMineRouteImport.update({
  id: '/learn/mine',
  path: '/learn/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsIdRoute = InstructorsIdRouteImport.update({
  id: '/instructors/$id',
  path: '/instructors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorProfileRoute = InstructorProfileRouteImport.update({
  id: '/instructor/profile',
  path: '/instructor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCallbackRoute = CheckoutCallbackRouteImport.update({
  id: '/checkout/callback',
  path: '/checkout/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrityRoute = AdminIntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => AdminRoute,
} as any)
const TeachersPathsIndexRoute = TeachersPathsIndexRouteImport.update({
  id: '/teachers/paths/',
  path: '/teachers/paths/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersCoursesIndexRoute = TeachersCoursesIndexRouteImport.update({
  id: '/teachers/courses/',
  path: '/teachers/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersCohortsIndexRoute = TeachersCohortsIndexRouteImport.update({
  id: '/teachers/cohorts/',
  path: '/teachers/cohorts/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorPathsIndexRoute = InstructorPathsIndexRouteImport.update({
  id: '/instructor/paths/',
  path: '/instructor/paths/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorEarningsIndexRoute = InstructorEarningsIndexRouteImport.update({
  id: '/instructor/earnings/',
  path: '/instructor/earnings/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorCoursesIndexRoute = InstructorCoursesIndexRouteImport.update({
  id: '/instructor/courses/',
  path: '/instructor/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorCohortsIndexRoute = InstructorCohortsIndexRouteImport.update({
  id: '/instructor/cohorts/',
  path: '/instructor/cohorts/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorAnalyticsIndexRoute =
  InstructorAnalyticsIndexRouteImport.update({
    id: '/instructor/analytics/',
    path: '/instructor/analytics/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsIndexRoute = AdminPayoutsIndexRouteImport.update({
  id: '/payouts/',
  path: '/payouts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPathsIndexRoute = AdminPathsIndexRouteImport.update({
  id: '/paths/',
  path: '/paths/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEarningsIndexRoute = AdminEarningsIndexRouteImport.update({
  id: '/earnings/',
  path: '/earnings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCohortsIndexRoute = AdminCohortsIndexRouteImport.update({
  id: '/cohorts/',
  path: '/cohorts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AdminRoute,
} as any)
const TeachersPathsSlugRoute = TeachersPathsSlugRouteImport.update({
  id: '/teachers/paths/$slug',
  path: '/teachers/paths/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersCoursesSlugRoute = TeachersCoursesSlugRouteImport.update({
  id: '/teachers/courses/$slug',
  path: '/teachers/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersCohortsSlugRoute = TeachersCohortsSlugRouteImport.update({
  id: '/teachers/cohorts/$slug',
  path: '/teachers/cohorts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnProjectProjectIdRoute = LearnProjectProjectIdRouteImport.update({
  id: '/learn/project/$projectId',
  path: '/learn/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPeerReviewProjectIdRoute =
  LearnPeerReviewProjectIdRouteImport.update({
    id: '/learn/peer-review/$projectId',
    path: '/learn/peer-review/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnPathPathIdRoute = LearnPathPathIdRouteImport.update({
  id: '/learn/path/$pathId',
  path: '/learn/path/$pathId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonLessonIdRoute = LearnLessonLessonIdRouteImport.update({
  id: '/learn/lesson/$lessonId',
  path: '/learn/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnGroupsGroupIdRoute = LearnGroupsGroupIdRouteImport.update({
  id: '/learn/groups/$groupId',
  path: '/learn/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseCourseIdRoute = LearnCourseCourseIdRouteImport.update({
  id: '/learn/course/$courseId',
  path: '/learn/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCohortCohortIdRoute = LearnCohortCohortIdRouteImport.update({
  id: '/learn/cohort/$cohortId',
  path: '/learn/cohort/$cohortId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnAssessmentAssessmentIdRoute =
  LearnAssessmentAssessmentIdRouteImport.update({
    id: '/learn/assessment/$assessmentId',
    path: '/learn/assessment/$assessmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstructorProjectsProjectIdRoute =
  InstructorProjectsProjectIdRouteImport.update({
    id: '/instructor/projects/$projectId',
    path: '/instructor/projects/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstructorProjectSubmissionsProjectIdRoute =
  InstructorProjectSubmissionsProjectIdRouteImport.update({
    id: '/instructor/project-submissions/$projectId',
    path: '/instructor/project-submissions/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstructorPathsPathIdRoute = InstructorPathsPathIdRouteImport.update({
  id: '/instructor/paths/$pathId',
  path: '/instructor/paths/$pathId',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorLessonsLessonIdRoute =
  InstructorLessonsLessonIdRouteImport.update({
    id: '/instructor/lessons/$lessonId',
    path: '/instructor/lessons/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstructorCoursesCourseIdRoute =
  InstructorCoursesCourseIdRouteImport.update({
    id: '/instructor/courses/$courseId',
    path: '/instructor/courses/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstructorCohortsCohortIdRoute =
  InstructorCohortsCohortIdRouteImport.update({
    id: '/instructor/cohorts/$cohortId',
    path: '/instructor/cohorts/$cohortId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstructorAttemptReportsAssessmentIdRoute =
  InstructorAttemptReportsAssessmentIdRouteImport.update({
    id: '/instructor/attempt-reports/$assessmentId',
    path: '/instructor/attempt-reports/$assessmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstructorAssessmentsAssessmentIdRoute =
  InstructorAssessmentsAssessmentIdRouteImport.update({
    id: '/instructor/assessments/$assessmentId',
    path: '/instructor/assessments/$assessmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FacilitatorCohortsCohortIdRoute =
  FacilitatorCohortsCohortIdRouteImport.update({
    id: '/facilitator/cohorts/$cohortId',
    path: '/facilitator/cohorts/$cohortId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProjectsProjectIdRoute = AdminProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectSubmissionsProjectIdRoute =
  AdminProjectSubmissionsProjectIdRouteImport.update({
    id: '/project-submissions/$projectId',
    path: '/project-submissions/$projectId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPathsPathIdRoute = AdminPathsPathIdRouteImport.update({
  id: '/paths/$pathId',
  path: '/paths/$pathId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsLessonIdRoute = AdminLessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesCourseIdRoute = AdminCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCohortsCohortIdRoute = AdminCohortsCohortIdRouteImport.update({
  id: '/cohorts/$cohortId',
  path: '/cohorts/$cohortId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogPostIdRoute = AdminBlogPostIdRouteImport.update({
  id: '/blog/$postId',
  path: '/blog/$postId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttemptReportsAssessmentIdRoute =
  AdminAttemptReportsAssessmentIdRouteImport.update({
    id: '/attempt-reports/$assessmentId',
    path: '/attempt-reports/$assessmentId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAssessmentsAssessmentIdRoute =
  AdminAssessmentsAssessmentIdRouteImport.update({
    id: '/assessments/$assessmentId',
    path: '/assessments/$assessmentId',
    getParentRoute: () => AdminRoute,
  } as any)
const InstructorAnalyticsEntityTypeEntityIdRoute =
  InstructorAnalyticsEntityTypeEntityIdRouteImport.update({
    id: '/instructor/analytics/$entityType/$entityId',
    path: '/instructor/analytics/$entityType/$entityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAnalyticsEntityTypeEntityIdRoute =
  AdminAnalyticsEntityTypeEntityIdRouteImport.update({
    id: '/analytics/$entityType/$entityId',
    path: '/analytics/$entityType/$entityId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/2fa': typeof R2faRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/community': typeof CommunityRoute
  '/continue': typeof ContinueRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/integrity': typeof AdminIntegrityRoute
  '/admin/profile': typeof AdminProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructors/$id': typeof InstructorsIdRoute
  '/learn/mine': typeof LearnMineRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/facilitator/': typeof FacilitatorIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/admin/assessments/$assessmentId': typeof AdminAssessmentsAssessmentIdRoute
  '/admin/attempt-reports/$assessmentId': typeof AdminAttemptReportsAssessmentIdRoute
  '/admin/blog/$postId': typeof AdminBlogPostIdRoute
  '/admin/cohorts/$cohortId': typeof AdminCohortsCohortIdRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/admin/paths/$pathId': typeof AdminPathsPathIdRoute
  '/admin/project-submissions/$projectId': typeof AdminProjectSubmissionsProjectIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/facilitator/cohorts/$cohortId': typeof FacilitatorCohortsCohortIdRoute
  '/instructor/assessments/$assessmentId': typeof InstructorAssessmentsAssessmentIdRoute
  '/instructor/attempt-reports/$assessmentId': typeof InstructorAttemptReportsAssessmentIdRoute
  '/instructor/cohorts/$cohortId': typeof InstructorCohortsCohortIdRoute
  '/instructor/courses/$courseId': typeof InstructorCoursesCourseIdRoute
  '/instructor/lessons/$lessonId': typeof InstructorLessonsLessonIdRoute
  '/instructor/paths/$pathId': typeof InstructorPathsPathIdRoute
  '/instructor/project-submissions/$projectId': typeof InstructorProjectSubmissionsProjectIdRoute
  '/instructor/projects/$projectId': typeof InstructorProjectsProjectIdRoute
  '/learn/assessment/$assessmentId': typeof LearnAssessmentAssessmentIdRoute
  '/learn/cohort/$cohortId': typeof LearnCohortCohortIdRoute
  '/learn/course/$courseId': typeof LearnCourseCourseIdRoute
  '/learn/groups/$groupId': typeof LearnGroupsGroupIdRoute
  '/learn/lesson/$lessonId': typeof LearnLessonLessonIdRoute
  '/learn/path/$pathId': typeof LearnPathPathIdRoute
  '/learn/peer-review/$projectId': typeof LearnPeerReviewProjectIdRoute
  '/learn/project/$projectId': typeof LearnProjectProjectIdRoute
  '/teachers/cohorts/$slug': typeof TeachersCohortsSlugRoute
  '/teachers/courses/$slug': typeof TeachersCoursesSlugRoute
  '/teachers/paths/$slug': typeof TeachersPathsSlugRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/cohorts/': typeof AdminCohortsIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/earnings/': typeof AdminEarningsIndexRoute
  '/admin/paths/': typeof AdminPathsIndexRoute
  '/admin/payouts/': typeof AdminPayoutsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/instructor/analytics/': typeof InstructorAnalyticsIndexRoute
  '/instructor/cohorts/': typeof InstructorCohortsIndexRoute
  '/instructor/courses/': typeof InstructorCoursesIndexRoute
  '/instructor/earnings/': typeof InstructorEarningsIndexRoute
  '/instructor/paths/': typeof InstructorPathsIndexRoute
  '/teachers/cohorts/': typeof TeachersCohortsIndexRoute
  '/teachers/courses/': typeof TeachersCoursesIndexRoute
  '/teachers/paths/': typeof TeachersPathsIndexRoute
  '/admin/analytics/$entityType/$entityId': typeof AdminAnalyticsEntityTypeEntityIdRoute
  '/instructor/analytics/$entityType/$entityId': typeof InstructorAnalyticsEntityTypeEntityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/2fa': typeof R2faRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/continue': typeof ContinueRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/integrity': typeof AdminIntegrityRoute
  '/admin/profile': typeof AdminProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructors/$id': typeof InstructorsIdRoute
  '/learn/mine': typeof LearnMineRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/facilitator': typeof FacilitatorIndexRoute
  '/instructor': typeof InstructorIndexRoute
  '/teachers': typeof TeachersIndexRoute
  '/admin/assessments/$assessmentId': typeof AdminAssessmentsAssessmentIdRoute
  '/admin/attempt-reports/$assessmentId': typeof AdminAttemptReportsAssessmentIdRoute
  '/admin/blog/$postId': typeof AdminBlogPostIdRoute
  '/admin/cohorts/$cohortId': typeof AdminCohortsCohortIdRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/admin/paths/$pathId': typeof AdminPathsPathIdRoute
  '/admin/project-submissions/$projectId': typeof AdminProjectSubmissionsProjectIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/facilitator/cohorts/$cohortId': typeof FacilitatorCohortsCohortIdRoute
  '/instructor/assessments/$assessmentId': typeof InstructorAssessmentsAssessmentIdRoute
  '/instructor/attempt-reports/$assessmentId': typeof InstructorAttemptReportsAssessmentIdRoute
  '/instructor/cohorts/$cohortId': typeof InstructorCohortsCohortIdRoute
  '/instructor/courses/$courseId': typeof InstructorCoursesCourseIdRoute
  '/instructor/lessons/$lessonId': typeof InstructorLessonsLessonIdRoute
  '/instructor/paths/$pathId': typeof InstructorPathsPathIdRoute
  '/instructor/project-submissions/$projectId': typeof InstructorProjectSubmissionsProjectIdRoute
  '/instructor/projects/$projectId': typeof InstructorProjectsProjectIdRoute
  '/learn/assessment/$assessmentId': typeof LearnAssessmentAssessmentIdRoute
  '/learn/cohort/$cohortId': typeof LearnCohortCohortIdRoute
  '/learn/course/$courseId': typeof LearnCourseCourseIdRoute
  '/learn/groups/$groupId': typeof LearnGroupsGroupIdRoute
  '/learn/lesson/$lessonId': typeof LearnLessonLessonIdRoute
  '/learn/path/$pathId': typeof LearnPathPathIdRoute
  '/learn/peer-review/$projectId': typeof LearnPeerReviewProjectIdRoute
  '/learn/project/$projectId': typeof LearnProjectProjectIdRoute
  '/teachers/cohorts/$slug': typeof TeachersCohortsSlugRoute
  '/teachers/courses/$slug': typeof TeachersCoursesSlugRoute
  '/teachers/paths/$slug': typeof TeachersPathsSlugRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/cohorts': typeof AdminCohortsIndexRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/earnings': typeof AdminEarningsIndexRoute
  '/admin/paths': typeof AdminPathsIndexRoute
  '/admin/payouts': typeof AdminPayoutsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/instructor/analytics': typeof InstructorAnalyticsIndexRoute
  '/instructor/cohorts': typeof InstructorCohortsIndexRoute
  '/instructor/courses': typeof InstructorCoursesIndexRoute
  '/instructor/earnings': typeof InstructorEarningsIndexRoute
  '/instructor/paths': typeof InstructorPathsIndexRoute
  '/teachers/cohorts': typeof TeachersCohortsIndexRoute
  '/teachers/courses': typeof TeachersCoursesIndexRoute
  '/teachers/paths': typeof TeachersPathsIndexRoute
  '/admin/analytics/$entityType/$entityId': typeof AdminAnalyticsEntityTypeEntityIdRoute
  '/instructor/analytics/$entityType/$entityId': typeof InstructorAnalyticsEntityTypeEntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/2fa': typeof R2faRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/community': typeof CommunityRoute
  '/continue': typeof ContinueRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/integrity': typeof AdminIntegrityRoute
  '/admin/profile': typeof AdminProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructors/$id': typeof InstructorsIdRoute
  '/learn/mine': typeof LearnMineRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/facilitator/': typeof FacilitatorIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/admin/assessments/$assessmentId': typeof AdminAssessmentsAssessmentIdRoute
  '/admin/attempt-reports/$assessmentId': typeof AdminAttemptReportsAssessmentIdRoute
  '/admin/blog/$postId': typeof AdminBlogPostIdRoute
  '/admin/cohorts/$cohortId': typeof AdminCohortsCohortIdRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/admin/paths/$pathId': typeof AdminPathsPathIdRoute
  '/admin/project-submissions/$projectId': typeof AdminProjectSubmissionsProjectIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/facilitator/cohorts/$cohortId': typeof FacilitatorCohortsCohortIdRoute
  '/instructor/assessments/$assessmentId': typeof InstructorAssessmentsAssessmentIdRoute
  '/instructor/attempt-reports/$assessmentId': typeof InstructorAttemptReportsAssessmentIdRoute
  '/instructor/cohorts/$cohortId': typeof InstructorCohortsCohortIdRoute
  '/instructor/courses/$courseId': typeof InstructorCoursesCourseIdRoute
  '/instructor/lessons/$lessonId': typeof InstructorLessonsLessonIdRoute
  '/instructor/paths/$pathId': typeof InstructorPathsPathIdRoute
  '/instructor/project-submissions/$projectId': typeof InstructorProjectSubmissionsProjectIdRoute
  '/instructor/projects/$projectId': typeof InstructorProjectsProjectIdRoute
  '/learn/assessment/$assessmentId': typeof LearnAssessmentAssessmentIdRoute
  '/learn/cohort/$cohortId': typeof LearnCohortCohortIdRoute
  '/learn/course/$courseId': typeof LearnCourseCourseIdRoute
  '/learn/groups/$groupId': typeof LearnGroupsGroupIdRoute
  '/learn/lesson/$lessonId': typeof LearnLessonLessonIdRoute
  '/learn/path/$pathId': typeof LearnPathPathIdRoute
  '/learn/peer-review/$projectId': typeof LearnPeerReviewProjectIdRoute
  '/learn/project/$projectId': typeof LearnProjectProjectIdRoute
  '/teachers/cohorts/$slug': typeof TeachersCohortsSlugRoute
  '/teachers/courses/$slug': typeof TeachersCoursesSlugRoute
  '/teachers/paths/$slug': typeof TeachersPathsSlugRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/cohorts/': typeof AdminCohortsIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/earnings/': typeof AdminEarningsIndexRoute
  '/admin/paths/': typeof AdminPathsIndexRoute
  '/admin/payouts/': typeof AdminPayoutsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/instructor/analytics/': typeof InstructorAnalyticsIndexRoute
  '/instructor/cohorts/': typeof InstructorCohortsIndexRoute
  '/instructor/courses/': typeof InstructorCoursesIndexRoute
  '/instructor/earnings/': typeof InstructorEarningsIndexRoute
  '/instructor/paths/': typeof InstructorPathsIndexRoute
  '/teachers/cohorts/': typeof TeachersCohortsIndexRoute
  '/teachers/courses/': typeof TeachersCoursesIndexRoute
  '/teachers/paths/': typeof TeachersPathsIndexRoute
  '/admin/analytics/$entityType/$entityId': typeof AdminAnalyticsEntityTypeEntityIdRoute
  '/instructor/analytics/$entityType/$entityId': typeof InstructorAnalyticsEntityTypeEntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/2fa'
    | '/about'
    | '/admin'
    | '/community'
    | '/continue'
    | '/dashboard'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/verify-email'
    | '/admin/integrity'
    | '/admin/profile'
    | '/blog/$slug'
    | '/checkout/callback'
    | '/courses/$slug'
    | '/instructor/profile'
    | '/instructors/$id'
    | '/learn/mine'
    | '/lessons/$lessonId'
    | '/verify/$token'
    | '/admin/'
    | '/blog/'
    | '/facilitator/'
    | '/instructor/'
    | '/teachers/'
    | '/admin/assessments/$assessmentId'
    | '/admin/attempt-reports/$assessmentId'
    | '/admin/blog/$postId'
    | '/admin/cohorts/$cohortId'
    | '/admin/courses/$courseId'
    | '/admin/lessons/$lessonId'
    | '/admin/paths/$pathId'
    | '/admin/project-submissions/$projectId'
    | '/admin/projects/$projectId'
    | '/facilitator/cohorts/$cohortId'
    | '/instructor/assessments/$assessmentId'
    | '/instructor/attempt-reports/$assessmentId'
    | '/instructor/cohorts/$cohortId'
    | '/instructor/courses/$courseId'
    | '/instructor/lessons/$lessonId'
    | '/instructor/paths/$pathId'
    | '/instructor/project-submissions/$projectId'
    | '/instructor/projects/$projectId'
    | '/learn/assessment/$assessmentId'
    | '/learn/cohort/$cohortId'
    | '/learn/course/$courseId'
    | '/learn/groups/$groupId'
    | '/learn/lesson/$lessonId'
    | '/learn/path/$pathId'
    | '/learn/peer-review/$projectId'
    | '/learn/project/$projectId'
    | '/teachers/cohorts/$slug'
    | '/teachers/courses/$slug'
    | '/teachers/paths/$slug'
    | '/admin/analytics/'
    | '/admin/blog/'
    | '/admin/cohorts/'
    | '/admin/courses/'
    | '/admin/earnings/'
    | '/admin/paths/'
    | '/admin/payouts/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/instructor/analytics/'
    | '/instructor/cohorts/'
    | '/instructor/courses/'
    | '/instructor/earnings/'
    | '/instructor/paths/'
    | '/teachers/cohorts/'
    | '/teachers/courses/'
    | '/teachers/paths/'
    | '/admin/analytics/$entityType/$entityId'
    | '/instructor/analytics/$entityType/$entityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/2fa'
    | '/about'
    | '/community'
    | '/continue'
    | '/dashboard'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/verify-email'
    | '/admin/integrity'
    | '/admin/profile'
    | '/blog/$slug'
    | '/checkout/callback'
    | '/courses/$slug'
    | '/instructor/profile'
    | '/instructors/$id'
    | '/learn/mine'
    | '/lessons/$lessonId'
    | '/verify/$token'
    | '/admin'
    | '/blog'
    | '/facilitator'
    | '/instructor'
    | '/teachers'
    | '/admin/assessments/$assessmentId'
    | '/admin/attempt-reports/$assessmentId'
    | '/admin/blog/$postId'
    | '/admin/cohorts/$cohortId'
    | '/admin/courses/$courseId'
    | '/admin/lessons/$lessonId'
    | '/admin/paths/$pathId'
    | '/admin/project-submissions/$projectId'
    | '/admin/projects/$projectId'
    | '/facilitator/cohorts/$cohortId'
    | '/instructor/assessments/$assessmentId'
    | '/instructor/attempt-reports/$assessmentId'
    | '/instructor/cohorts/$cohortId'
    | '/instructor/courses/$courseId'
    | '/instructor/lessons/$lessonId'
    | '/instructor/paths/$pathId'
    | '/instructor/project-submissions/$projectId'
    | '/instructor/projects/$projectId'
    | '/learn/assessment/$assessmentId'
    | '/learn/cohort/$cohortId'
    | '/learn/course/$courseId'
    | '/learn/groups/$groupId'
    | '/learn/lesson/$lessonId'
    | '/learn/path/$pathId'
    | '/learn/peer-review/$projectId'
    | '/learn/project/$projectId'
    | '/teachers/cohorts/$slug'
    | '/teachers/courses/$slug'
    | '/teachers/paths/$slug'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/cohorts'
    | '/admin/courses'
    | '/admin/earnings'
    | '/admin/paths'
    | '/admin/payouts'
    | '/admin/settings'
    | '/admin/users'
    | '/instructor/analytics'
    | '/instructor/cohorts'
    | '/instructor/courses'
    | '/instructor/earnings'
    | '/instructor/paths'
    | '/teachers/cohorts'
    | '/teachers/courses'
    | '/teachers/paths'
    | '/admin/analytics/$entityType/$entityId'
    | '/instructor/analytics/$entityType/$entityId'
  id:
    | '__root__'
    | '/'
    | '/2fa'
    | '/about'
    | '/admin'
    | '/community'
    | '/continue'
    | '/dashboard'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/verify-email'
    | '/admin/integrity'
    | '/admin/profile'
    | '/blog/$slug'
    | '/checkout/callback'
    | '/courses/$slug'
    | '/instructor/profile'
    | '/instructors/$id'
    | '/learn/mine'
    | '/lessons/$lessonId'
    | '/verify/$token'
    | '/admin/'
    | '/blog/'
    | '/facilitator/'
    | '/instructor/'
    | '/teachers/'
    | '/admin/assessments/$assessmentId'
    | '/admin/attempt-reports/$assessmentId'
    | '/admin/blog/$postId'
    | '/admin/cohorts/$cohortId'
    | '/admin/courses/$courseId'
    | '/admin/lessons/$lessonId'
    | '/admin/paths/$pathId'
    | '/admin/project-submissions/$projectId'
    | '/admin/projects/$projectId'
    | '/facilitator/cohorts/$cohortId'
    | '/instructor/assessments/$assessmentId'
    | '/instructor/attempt-reports/$assessmentId'
    | '/instructor/cohorts/$cohortId'
    | '/instructor/courses/$courseId'
    | '/instructor/lessons/$lessonId'
    | '/instructor/paths/$pathId'
    | '/instructor/project-submissions/$projectId'
    | '/instructor/projects/$projectId'
    | '/learn/assessment/$assessmentId'
    | '/learn/cohort/$cohortId'
    | '/learn/course/$courseId'
    | '/learn/groups/$groupId'
    | '/learn/lesson/$lessonId'
    | '/learn/path/$pathId'
    | '/learn/peer-review/$projectId'
    | '/learn/project/$projectId'
    | '/teachers/cohorts/$slug'
    | '/teachers/courses/$slug'
    | '/teachers/paths/$slug'
    | '/admin/analytics/'
    | '/admin/blog/'
    | '/admin/cohorts/'
    | '/admin/courses/'
    | '/admin/earnings/'
    | '/admin/paths/'
    | '/admin/payouts/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/instructor/analytics/'
    | '/instructor/cohorts/'
    | '/instructor/courses/'
    | '/instructor/earnings/'
    | '/instructor/paths/'
    | '/teachers/cohorts/'
    | '/teachers/courses/'
    | '/teachers/paths/'
    | '/admin/analytics/$entityType/$entityId'
    | '/instructor/analytics/$entityType/$entityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R2faRoute: typeof R2faRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  ContinueRoute: typeof ContinueRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutCallbackRoute: typeof CheckoutCallbackRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  InstructorProfileRoute: typeof InstructorProfileRoute
  InstructorsIdRoute: typeof InstructorsIdRoute
  LearnMineRoute: typeof LearnMineRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FacilitatorIndexRoute: typeof FacilitatorIndexRoute
  InstructorIndexRoute: typeof InstructorIndexRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
  FacilitatorCohortsCohortIdRoute: typeof FacilitatorCohortsCohortIdRoute
  InstructorAssessmentsAssessmentIdRoute: typeof InstructorAssessmentsAssessmentIdRoute
  InstructorAttemptReportsAssessmentIdRoute: typeof InstructorAttemptReportsAssessmentIdRoute
  InstructorCohortsCohortIdRoute: typeof InstructorCohortsCohortIdRoute
  InstructorCoursesCourseIdRoute: typeof InstructorCoursesCourseIdRoute
  InstructorLessonsLessonIdRoute: typeof InstructorLessonsLessonIdRoute
  InstructorPathsPathIdRoute: typeof InstructorPathsPathIdRoute
  InstructorProjectSubmissionsProjectIdRoute: typeof InstructorProjectSubmissionsProjectIdRoute
  InstructorProjectsProjectIdRoute: typeof InstructorProjectsProjectIdRoute
  LearnAssessmentAssessmentIdRoute: typeof LearnAssessmentAssessmentIdRoute
  LearnCohortCohortIdRoute: typeof LearnCohortCohortIdRoute
  LearnCourseCourseIdRoute: typeof LearnCourseCourseIdRoute
  LearnGroupsGroupIdRoute: typeof LearnGroupsGroupIdRoute
  LearnLessonLessonIdRoute: typeof LearnLessonLessonIdRoute
  LearnPathPathIdRoute: typeof LearnPathPathIdRoute
  LearnPeerReviewProjectIdRoute: typeof LearnPeerReviewProjectIdRoute
  LearnProjectProjectIdRoute: typeof LearnProjectProjectIdRoute
  TeachersCohortsSlugRoute: typeof TeachersCohortsSlugRoute
  TeachersCoursesSlugRoute: typeof TeachersCoursesSlugRoute
  TeachersPathsSlugRoute: typeof TeachersPathsSlugRoute
  InstructorAnalyticsIndexRoute: typeof InstructorAnalyticsIndexRoute
  InstructorCohortsIndexRoute: typeof InstructorCohortsIndexRoute
  InstructorCoursesIndexRoute: typeof InstructorCoursesIndexRoute
  InstructorEarningsIndexRoute: typeof InstructorEarningsIndexRoute
  InstructorPathsIndexRoute: typeof InstructorPathsIndexRoute
  TeachersCohortsIndexRoute: typeof TeachersCohortsIndexRoute
  TeachersCoursesIndexRoute: typeof TeachersCoursesIndexRoute
  TeachersPathsIndexRoute: typeof TeachersPathsIndexRoute
  InstructorAnalyticsEntityTypeEntityIdRoute: typeof InstructorAnalyticsEntityTypeEntityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continue': {
      id: '/continue'
      path: '/continue'
      fullPath: '/continue'
      preLoaderRoute: typeof ContinueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2fa': {
      id: '/2fa'
      path: '/2fa'
      fullPath: '/2fa'
      preLoaderRoute: typeof R2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/': {
      id: '/instructor/'
      path: '/instructor'
      fullPath: '/instructor/'
      preLoaderRoute: typeof InstructorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilitator/': {
      id: '/facilitator/'
      path: '/facilitator'
      fullPath: '/facilitator/'
      preLoaderRoute: typeof FacilitatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/mine': {
      id: '/learn/mine'
      path: '/learn/mine'
      fullPath: '/learn/mine'
      preLoaderRoute: typeof LearnMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors/$id': {
      id: '/instructors/$id'
      path: '/instructors/$id'
      fullPath: '/instructors/$id'
      preLoaderRoute: typeof InstructorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/profile': {
      id: '/instructor/profile'
      path: '/instructor/profile'
      fullPath: '/instructor/profile'
      preLoaderRoute: typeof InstructorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/callback': {
      id: '/checkout/callback'
      path: '/checkout/callback'
      fullPath: '/checkout/callback'
      preLoaderRoute: typeof CheckoutCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrity': {
      id: '/admin/integrity'
      path: '/integrity'
      fullPath: '/admin/integrity'
      preLoaderRoute: typeof AdminIntegrityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teachers/paths/': {
      id: '/teachers/paths/'
      path: '/teachers/paths'
      fullPath: '/teachers/paths/'
      preLoaderRoute: typeof TeachersPathsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/courses/': {
      id: '/teachers/courses/'
      path: '/teachers/courses'
      fullPath: '/teachers/courses/'
      preLoaderRoute: typeof TeachersCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/cohorts/': {
      id: '/teachers/cohorts/'
      path: '/teachers/cohorts'
      fullPath: '/teachers/cohorts/'
      preLoaderRoute: typeof TeachersCohortsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/paths/': {
      id: '/instructor/paths/'
      path: '/instructor/paths'
      fullPath: '/instructor/paths/'
      preLoaderRoute: typeof InstructorPathsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/earnings/': {
      id: '/instructor/earnings/'
      path: '/instructor/earnings'
      fullPath: '/instructor/earnings/'
      preLoaderRoute: typeof InstructorEarningsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/courses/': {
      id: '/instructor/courses/'
      path: '/instructor/courses'
      fullPath: '/instructor/courses/'
      preLoaderRoute: typeof InstructorCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/cohorts/': {
      id: '/instructor/cohorts/'
      path: '/instructor/cohorts'
      fullPath: '/instructor/cohorts/'
      preLoaderRoute: typeof InstructorCohortsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/analytics/': {
      id: '/instructor/analytics/'
      path: '/instructor/analytics'
      fullPath: '/instructor/analytics/'
      preLoaderRoute: typeof InstructorAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts/': {
      id: '/admin/payouts/'
      path: '/payouts'
      fullPath: '/admin/payouts/'
      preLoaderRoute: typeof AdminPayoutsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paths/': {
      id: '/admin/paths/'
      path: '/paths'
      fullPath: '/admin/paths/'
      preLoaderRoute: typeof AdminPathsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/earnings/': {
      id: '/admin/earnings/'
      path: '/earnings'
      fullPath: '/admin/earnings/'
      preLoaderRoute: typeof AdminEarningsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cohorts/': {
      id: '/admin/cohorts/'
      path: '/cohorts'
      fullPath: '/admin/cohorts/'
      preLoaderRoute: typeof AdminCohortsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/analytics'
      fullPath: '/admin/analytics/'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teachers/paths/$slug': {
      id: '/teachers/paths/$slug'
      path: '/teachers/paths/$slug'
      fullPath: '/teachers/paths/$slug'
      preLoaderRoute: typeof TeachersPathsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/courses/$slug': {
      id: '/teachers/courses/$slug'
      path: '/teachers/courses/$slug'
      fullPath: '/teachers/courses/$slug'
      preLoaderRoute: typeof TeachersCoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/cohorts/$slug': {
      id: '/teachers/cohorts/$slug'
      path: '/teachers/cohorts/$slug'
      fullPath: '/teachers/cohorts/$slug'
      preLoaderRoute: typeof TeachersCohortsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/project/$projectId': {
      id: '/learn/project/$projectId'
      path: '/learn/project/$projectId'
      fullPath: '/learn/project/$projectId'
      preLoaderRoute: typeof LearnProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/peer-review/$projectId': {
      id: '/learn/peer-review/$projectId'
      path: '/learn/peer-review/$projectId'
      fullPath: '/learn/peer-review/$projectId'
      preLoaderRoute: typeof LearnPeerReviewProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/path/$pathId': {
      id: '/learn/path/$pathId'
      path: '/learn/path/$pathId'
      fullPath: '/learn/path/$pathId'
      preLoaderRoute: typeof LearnPathPathIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/lesson/$lessonId': {
      id: '/learn/lesson/$lessonId'
      path: '/learn/lesson/$lessonId'
      fullPath: '/learn/lesson/$lessonId'
      preLoaderRoute: typeof LearnLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/groups/$groupId': {
      id: '/learn/groups/$groupId'
      path: '/learn/groups/$groupId'
      fullPath: '/learn/groups/$groupId'
      preLoaderRoute: typeof LearnGroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/course/$courseId': {
      id: '/learn/course/$courseId'
      path: '/learn/course/$courseId'
      fullPath: '/learn/course/$courseId'
      preLoaderRoute: typeof LearnCourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/cohort/$cohortId': {
      id: '/learn/cohort/$cohortId'
      path: '/learn/cohort/$cohortId'
      fullPath: '/learn/cohort/$cohortId'
      preLoaderRoute: typeof LearnCohortCohortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/assessment/$assessmentId': {
      id: '/learn/assessment/$assessmentId'
      path: '/learn/assessment/$assessmentId'
      fullPath: '/learn/assessment/$assessmentId'
      preLoaderRoute: typeof LearnAssessmentAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/projects/$projectId': {
      id: '/instructor/projects/$projectId'
      path: '/instructor/projects/$projectId'
      fullPath: '/instructor/projects/$projectId'
      preLoaderRoute: typeof InstructorProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/project-submissions/$projectId': {
      id: '/instructor/project-submissions/$projectId'
      path: '/instructor/project-submissions/$projectId'
      fullPath: '/instructor/project-submissions/$projectId'
      preLoaderRoute: typeof InstructorProjectSubmissionsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/paths/$pathId': {
      id: '/instructor/paths/$pathId'
      path: '/instructor/paths/$pathId'
      fullPath: '/instructor/paths/$pathId'
      preLoaderRoute: typeof InstructorPathsPathIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/lessons/$lessonId': {
      id: '/instructor/lessons/$lessonId'
      path: '/instructor/lessons/$lessonId'
      fullPath: '/instructor/lessons/$lessonId'
      preLoaderRoute: typeof InstructorLessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/courses/$courseId': {
      id: '/instructor/courses/$courseId'
      path: '/instructor/courses/$courseId'
      fullPath: '/instructor/courses/$courseId'
      preLoaderRoute: typeof InstructorCoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/cohorts/$cohortId': {
      id: '/instructor/cohorts/$cohortId'
      path: '/instructor/cohorts/$cohortId'
      fullPath: '/instructor/cohorts/$cohortId'
      preLoaderRoute: typeof InstructorCohortsCohortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/attempt-reports/$assessmentId': {
      id: '/instructor/attempt-reports/$assessmentId'
      path: '/instructor/attempt-reports/$assessmentId'
      fullPath: '/instructor/attempt-reports/$assessmentId'
      preLoaderRoute: typeof InstructorAttemptReportsAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/assessments/$assessmentId': {
      id: '/instructor/assessments/$assessmentId'
      path: '/instructor/assessments/$assessmentId'
      fullPath: '/instructor/assessments/$assessmentId'
      preLoaderRoute: typeof InstructorAssessmentsAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilitator/cohorts/$cohortId': {
      id: '/facilitator/cohorts/$cohortId'
      path: '/facilitator/cohorts/$cohortId'
      fullPath: '/facilitator/cohorts/$cohortId'
      preLoaderRoute: typeof FacilitatorCohortsCohortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$projectId': {
      id: '/admin/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AdminProjectsProjectIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/project-submissions/$projectId': {
      id: '/admin/project-submissions/$projectId'
      path: '/project-submissions/$projectId'
      fullPath: '/admin/project-submissions/$projectId'
      preLoaderRoute: typeof AdminProjectSubmissionsProjectIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paths/$pathId': {
      id: '/admin/paths/$pathId'
      path: '/paths/$pathId'
      fullPath: '/admin/paths/$pathId'
      preLoaderRoute: typeof AdminPathsPathIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons/$lessonId': {
      id: '/admin/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/admin/lessons/$lessonId'
      preLoaderRoute: typeof AdminLessonsLessonIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/$courseId': {
      id: '/admin/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cohorts/$cohortId': {
      id: '/admin/cohorts/$cohortId'
      path: '/cohorts/$cohortId'
      fullPath: '/admin/cohorts/$cohortId'
      preLoaderRoute: typeof AdminCohortsCohortIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$postId': {
      id: '/admin/blog/$postId'
      path: '/blog/$postId'
      fullPath: '/admin/blog/$postId'
      preLoaderRoute: typeof AdminBlogPostIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attempt-reports/$assessmentId': {
      id: '/admin/attempt-reports/$assessmentId'
      path: '/attempt-reports/$assessmentId'
      fullPath: '/admin/attempt-reports/$assessmentId'
      preLoaderRoute: typeof AdminAttemptReportsAssessmentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assessments/$assessmentId': {
      id: '/admin/assessments/$assessmentId'
      path: '/assessments/$assessmentId'
      fullPath: '/admin/assessments/$assessmentId'
      preLoaderRoute: typeof AdminAssessmentsAssessmentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/instructor/analytics/$entityType/$entityId': {
      id: '/instructor/analytics/$entityType/$entityId'
      path: '/instructor/analytics/$entityType/$entityId'
      fullPath: '/instructor/analytics/$entityType/$entityId'
      preLoaderRoute: typeof InstructorAnalyticsEntityTypeEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics/$entityType/$entityId': {
      id: '/admin/analytics/$entityType/$entityId'
      path: '/analytics/$entityType/$entityId'
      fullPath: '/admin/analytics/$entityType/$entityId'
      preLoaderRoute: typeof AdminAnalyticsEntityTypeEntityIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIntegrityRoute: typeof AdminIntegrityRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAssessmentsAssessmentIdRoute: typeof AdminAssessmentsAssessmentIdRoute
  AdminAttemptReportsAssessmentIdRoute: typeof AdminAttemptReportsAssessmentIdRoute
  AdminBlogPostIdRoute: typeof AdminBlogPostIdRoute
  AdminCohortsCohortIdRoute: typeof AdminCohortsCohortIdRoute
  AdminCoursesCourseIdRoute: typeof AdminCoursesCourseIdRoute
  AdminLessonsLessonIdRoute: typeof AdminLessonsLessonIdRoute
  AdminPathsPathIdRoute: typeof AdminPathsPathIdRoute
  AdminProjectSubmissionsProjectIdRoute: typeof AdminProjectSubmissionsProjectIdRoute
  AdminProjectsProjectIdRoute: typeof AdminProjectsProjectIdRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminCohortsIndexRoute: typeof AdminCohortsIndexRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminEarningsIndexRoute: typeof AdminEarningsIndexRoute
  AdminPathsIndexRoute: typeof AdminPathsIndexRoute
  AdminPayoutsIndexRoute: typeof AdminPayoutsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminAnalyticsEntityTypeEntityIdRoute: typeof AdminAnalyticsEntityTypeEntityIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIntegrityRoute: AdminIntegrityRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAssessmentsAssessmentIdRoute: AdminAssessmentsAssessmentIdRoute,
  AdminAttemptReportsAssessmentIdRoute: AdminAttemptReportsAssessmentIdRoute,
  AdminBlogPostIdRoute: AdminBlogPostIdRoute,
  AdminCohortsCohortIdRoute: AdminCohortsCohortIdRoute,
  AdminCoursesCourseIdRoute: AdminCoursesCourseIdRoute,
  AdminLessonsLessonIdRoute: AdminLessonsLessonIdRoute,
  AdminPathsPathIdRoute: AdminPathsPathIdRoute,
  AdminProjectSubmissionsProjectIdRoute: AdminProjectSubmissionsProjectIdRoute,
  AdminProjectsProjectIdRoute: AdminProjectsProjectIdRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminCohortsIndexRoute: AdminCohortsIndexRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminEarningsIndexRoute: AdminEarningsIndexRoute,
  AdminPathsIndexRoute: AdminPathsIndexRoute,
  AdminPayoutsIndexRoute: AdminPayoutsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminAnalyticsEntityTypeEntityIdRoute: AdminAnalyticsEntityTypeEntityIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R2faRoute: R2faRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CommunityRoute: CommunityRoute,
  ContinueRoute: ContinueRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutCallbackRoute: CheckoutCallbackRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  InstructorProfileRoute: InstructorProfileRoute,
  InstructorsIdRoute: InstructorsIdRoute,
  LearnMineRoute: LearnMineRoute,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  VerifyTokenRoute: VerifyTokenRoute,
  BlogIndexRoute: BlogIndexRoute,
  FacilitatorIndexRoute: FacilitatorIndexRoute,
  InstructorIndexRoute: InstructorIndexRoute,
  TeachersIndexRoute: TeachersIndexRoute,
  FacilitatorCohortsCohortIdRoute: FacilitatorCohortsCohortIdRoute,
  InstructorAssessmentsAssessmentIdRoute:
    InstructorAssessmentsAssessmentIdRoute,
  InstructorAttemptReportsAssessmentIdRoute:
    InstructorAttemptReportsAssessmentIdRoute,
  InstructorCohortsCohortIdRoute: InstructorCohortsCohortIdRoute,
  InstructorCoursesCourseIdRoute: InstructorCoursesCourseIdRoute,
  InstructorLessonsLessonIdRoute: InstructorLessonsLessonIdRoute,
  InstructorPathsPathIdRoute: InstructorPathsPathIdRoute,
  InstructorProjectSubmissionsProjectIdRoute:
    InstructorProjectSubmissionsProjectIdRoute,
  InstructorProjectsProjectIdRoute: InstructorProjectsProjectIdRoute,
  LearnAssessmentAssessmentIdRoute: LearnAssessmentAssessmentIdRoute,
  LearnCohortCohortIdRoute: LearnCohortCohortIdRoute,
  LearnCourseCourseIdRoute: LearnCourseCourseIdRoute,
  LearnGroupsGroupIdRoute: LearnGroupsGroupIdRoute,
  LearnLessonLessonIdRoute: LearnLessonLessonIdRoute,
  LearnPathPathIdRoute: LearnPathPathIdRoute,
  LearnPeerReviewProjectIdRoute: LearnPeerReviewProjectIdRoute,
  LearnProjectProjectIdRoute: LearnProjectProjectIdRoute,
  TeachersCohortsSlugRoute: TeachersCohortsSlugRoute,
  TeachersCoursesSlugRoute: TeachersCoursesSlugRoute,
  TeachersPathsSlugRoute: TeachersPathsSlugRoute,
  InstructorAnalyticsIndexRoute: InstructorAnalyticsIndexRoute,
  InstructorCohortsIndexRoute: InstructorCohortsIndexRoute,
  InstructorCoursesIndexRoute: InstructorCoursesIndexRoute,
  InstructorEarningsIndexRoute: InstructorEarningsIndexRoute,
  InstructorPathsIndexRoute: InstructorPathsIndexRoute,
  TeachersCohortsIndexRoute: TeachersCohortsIndexRoute,
  TeachersCoursesIndexRoute: TeachersCoursesIndexRoute,
  TeachersPathsIndexRoute: TeachersPathsIndexRoute,
  InstructorAnalyticsEntityTypeEntityIdRoute:
    InstructorAnalyticsEntityTypeEntityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
